Misc. fixes to make packaging easier
Inrixia/Floatplane-Downloader pull request #222
Opened 2024-10-29 20:09 UTC by Noodlez1232

This includes various miscellaneous fixes and changes as described in the issue #221. My recommendation is to *not* squash this pull request on merging, since the commits are detailed in every change that is done.

2024-10-30 02:17 UTC, Inrixia requested changes
Linting and Builds are failing. 
You can run `pnpm run sanity` to do a lint and build check.
See my comments for everything else.

2024-10-30 02:17 UTC, Inrixia commented on src/lib/defaults.ts
> +		args.ffmpegPath = `${args.workPath}/${getBinaryFilename("ffmpeg", detectPlatform() )}`;
This logic doesn't belong here.
ffmpegPath logic should be moved to `lib/helpers/fetchFFMPEG.ts` as
```ts
export const ffmpegPath = args.ffmpegPath ?? `${args.dbPath}/ffmpeg`;
```

The rest should be removed and consolidated using `args.dbPath` as a prefix

2024-10-30 02:17 UTC, Inrixia commented on src/lib/helpers/fetchFFMPEG.ts
> -		if (fs.existsSync(`${path}${getBinaryFilename("ffmpeg", platform)}`) === false) {
Removing 
```ts
getBinaryFilename("ffmpeg", platform)
```

will cause ffmpeg to fail on certain platforms

2024-10-30 02:17 UTC, Inrixia commented on src/lib/helpers/fetchFFMPEG.ts
> +				basename(path),
This has to be **"ffmpeg"**

2024-10-30 02:17 UTC, Inrixia commented on src/lib/helpers/fetchFFMPEG.ts
> +		if (fs.existsSync(path) === false) {
Why strict equality check on a boolean? Just do
```ts
!fs.existsSync(path)
```

2024-10-30 02:17 UTC, Inrixia commented on src/lib/helpers/index.ts
> +export const DownloaderVersion = pjson.version;
This will likely cause binary builds to fail as they do not have a local package.json

2024-10-30 02:17 UTC, Inrixia commented on src/lib/helpers/index.ts
> +export const cookieJar = new CookieJar(new FileCookieStore(args.cookiesPath));
This should be
```ts
`${args.dbPath}/cookies.json`
```

2024-10-30 02:17 UTC, Inrixia commented on src/lib/Video.ts
> +				args.ffmpegPath,
This should use an exported path from `lib/helpers/fetchFFMPEG.ts`

2024-11-01 23:35 UTC, Inrixia commented
Closing due to inactivity. Feel free to re-open if you want to :)

2024-11-07 18:02 UTC, Noodlez1232 commented
Hi, sorry for the lack of response. I've been busy with uni. I don't have permission to re-open. I've worked on some of the problems you've mentioned, though, and responded to some of the resolutions you've given (including some I disagree with).

2024-11-07 18:04 UTC, Noodlez1232 commented on src/lib/helpers/index.ts
> +export const DownloaderVersion = pjson.version;
I've fixed this in my latest commit. The fix here is to move the sentinel outside package.json, and then just including it in the binary.

2024-11-07 18:10 UTC, Noodlez1232 commented on src/lib/defaults.ts
> +		args.ffmpegPath = `${args.workPath}/${getBinaryFilename("ffmpeg", detectPlatform() )}`;
Doing the logic in this order doesn't work (args.ffmpegPath isn't set by the time args are parsed, leading `ffmpegPath` to be always `${args.dbPath}/ffmpeg`.
I'll keep this in the argument parsing. Also this doesn't work on windows. `ffmpeg` is named `ffmpeg.exe`.

2024-11-07 18:37 UTC, Noodlez1232 commented on src/lib/defaults.ts
> +		args.ffmpegPath = `${args.workPath}/${getBinaryFilename("ffmpeg", detectPlatform() )}`;
Actually I take this back, my bad. I tested this and this worked.

2024-11-07 20:56 UTC, Inrixia commented
I am going to reopen this and close #225 to keep this discussion in one place.

2024-11-07 20:59 UTC, Inrixia commented on src/lib/helpers/index.ts
> +export const DownloaderVersion = pjson.version;
This has nothing to do with the sentinel text. This is about how the downloader fetches its version number.

In a built binary the package.json file doesn't exist so this will fail. Which is why the version was encoded into a file embedded into the binary.

2024-11-07 21:07 UTC, Inrixia requested changes

2024-11-07 21:07 UTC, Inrixia commented on package.json
> +		"injectLinux": "npx postject ./build/float-linux NODE_SEA_BLOB ./dist/float.blob --sentinel-fuse $(cat ./postject-sentinel.txt)"
This is causing builds to fail. There's no reason to not have the sentinel string here.

2024-11-07 21:07 UTC, Inrixia commented on src/lib/Attachment.ts
> +	private static readonly AttachmentsDB: Record<string, AttachmentInfo> = db<Record<string, AttachmentInfo>>(`${args.dbPath}/attachments.json`);
You shouldn't reference via args. Args should be merged onto settings. Unless I'm misremembering, let me know if they are seperate types

2024-11-07 21:07 UTC, Inrixia commented on src/lib/helpers/index.ts
> -import { getEnv, rebuildTypes, recursiveUpdate } from "@inrixia/helpers/object";
Why remove rebuildTypes?

2024-11-07 23:11 UTC, Noodlez1232 commented on src/lib/helpers/index.ts
> -import { getEnv, rebuildTypes, recursiveUpdate } from "@inrixia/helpers/object";
This was removed since it's not being used anymore. I was listening to the linter.

2024-11-07 23:11 UTC, Noodlez1232 commented on src/lib/Attachment.ts
> +	private static readonly AttachmentsDB: Record<string, AttachmentInfo> = db<Record<string, AttachmentInfo>>(`${args.dbPath}/attachments.json`);
Gotcha that was my bad. I'll fix that.

2024-11-07 23:12 UTC, Noodlez1232 commented on package.json
> +		"injectLinux": "npx postject ./build/float-linux NODE_SEA_BLOB ./dist/float.blob --sentinel-fuse $(cat ./postject-sentinel.txt)"
This acts differently on my machine. The sentinel string, when being built on my machine, causes build errors. I tried moving it out of the package.json since it was helping it build, but the CI is acting differently. I'll look into it more.

2024-11-07 23:16 UTC, Noodlez1232 commented on package.json
> +		"injectLinux": "npx postject ./build/float-linux NODE_SEA_BLOB ./dist/float.blob --sentinel-fuse $(cat ./postject-sentinel.txt)"
For clarification, the sentinel string on my machine was causing the exact error that's happening on the Windows machines, that's why I moved it out. I'll look into other fixes, since it really just moved the error somewhere else.

2024-11-07 23:34 UTC, Noodlez1232 commented on src/lib/Attachment.ts
> +	private static readonly AttachmentsDB: Record<string, AttachmentInfo> = db<Record<string, AttachmentInfo>>(`${args.dbPath}/attachments.json`);
Oh I remember why now. It's not a part of the Settings type. It's not valid. That's why it comes from args.

2024-11-08 00:13 UTC, Noodlez1232 commented on package.json
> +		"injectLinux": "npx postject ./build/float-linux NODE_SEA_BLOB ./dist/float.blob --sentinel-fuse $(cat ./postject-sentinel.txt)"
I've decided to just solve this in packaging with a custom patch, since nothing I seem to do will solve both problems, and I'd rather not break upstream.

2024-11-08 00:13 UTC, Noodlez1232 commented
I'd like to also migrate over the question of the settings.json from the other pull request. I was just wondering thoughts on that.

2024-11-08 00:31 UTC, Inrixia commented
> I'd like to also migrate over the question of the settings.json from the other pull request.

Could you copy paste it here thx.

2024-11-08 00:33 UTC, Inrixia requested changes

2024-11-08 00:33 UTC, Inrixia commented on src/lib/helpers/index.ts
> -rebuildTypes(argv, { ...defaultSettings, ...defaultArgs });
Sorry I should have clarified, I meant why was it removed from here.

Psure it's fairly important to coerce types from strings

2024-11-08 00:33 UTC, Noodlez1232 commented
I'd like to start discussion for the separation of settings.json as well.
Since settings.json includes information that could potentially be moved somewhere else (e.g. /etc), it may make sense to add an argument to move its path. The other states (attachments.json, cookies.json, etc.) can still be kept in ./db, since I agree this makes much more sense, but settings.json much like the path of ffmpeg can change based on the distro. (e.g. NixOS allowing setting of settings.json using its own language.)

2024-11-08 00:35 UTC, Inrixia commented
Re settings.json path I agree, and it's a open issue in #177

I remember there being a few issues with a chicken and egg situation though due to how settings are applied but it's not unworkable

2024-11-08 00:37 UTC, Noodlez1232 commented
Unfortunately I'll have to continue this tomorrow as I'm running out of time for the day. Thanks for being so active!

2024-11-08 00:41 UTC, Inrixia commented
No problem and no rush :)

Thanks for contributing

2024-11-08 05:34 UTC, Noodlez1232 commented on src/lib/helpers/index.ts
> -rebuildTypes(argv, { ...defaultSettings, ...defaultArgs });
I couldn't help myself so I checked this, and you're right. I was having trouble getting it working due to some problems with object referencing vs copying. I got that figured out.

2024-11-08 05:35 UTC, Noodlez1232 commented
I'll get the settings path changed and push tomorrow at some point. I've got an idea on how to accomplish that.

2024-11-17 06:50 UTC, Inrixia commented
Lemme know when this is ready for review

2024-11-17 22:41 UTC, Noodlez1232 commented
Oops my bad yeah It's ready for review I'll mark it as such

2024-12-24 01:42 UTC, Inrixia approved these changes
Sorry for taking a while to get to this, looks like its probably good. Will approve this

2024-12-24 01:48 UTC, Inrixia commented
@Noodlez1232 Can you fix the lockfile on your branch so I can run tests thx

2024-12-24 02:15 UTC, Noodlez1232 commented
@Inrixia Here we go. Hopefully that should work

2024-12-24 02:59 UTC, merged